version: "3.8"
services:
  web:
    entrypoint: ["watchmedo", "auto-restart", "--directory=.", "--pattern=*.py", "--recursive", "--", "python", "-m", "debugpy", "--listen", "0.0.0.0:5679", "run.py"]

  # vault:
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: root
  #     VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
  #   cap_add:
  #     - IPC_LOCK
  #   command: ["vault", "server", "-dev"]
  #   volumes: []