version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "5679:5679"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      VAULT_URL: http://vault:8200
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    init: true
    depends_on:
      - vault
    entrypoint: ["watchmedo", "auto-restart", "--directory=.", "--pattern=*.py", "--recursive", "--", "python", "-m", "debugpy", "--listen", "0.0.0.0:5679", "run.py"]


  vault:
    image: vault:1.13.0
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data

volumes:
  vault_data: